export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE' 

// About
export const REDUCE_TEAM_INDEX = 'REDUCE_TEAM_INDEX' 
export const INCREASE_TEAM_INDEX = 'INCREASE_TEAM_INDEX'
export const CHANGE_TEAM_INDEX = 'CHANGE_TEAM_INDEX'
//Partners
export const REDUCE_PARTNERS_INDEX = 'REDUCE_PARTNERS_INDEX' 
export const INCREASE_PARTNERS_INDEX = 'INCREASE_PARTNERS_INDE'
export const CHANGE_PARTNERS_INDEX = 'CHANGE_PARTNERS_INDEX'