const labels_en = {
    basicTitle: `Basic Page`,
    basicTitle2: `Detracto tincidunt constituto qui id, ex sit soleat habemus conceptam, et tation tollit nec.`,
    partnersTitle: `Partners`,
    joinIndex: `- Join the challenge`,
    joinTitle: `Play. Improve. Win!`,
    gameIndex: `- More coming soon`,
    gameTitle: `Games We Support`,
    featuresTitle: 'Features',
    whatFeaturesIndex: '- What is eMasters',
    whatFeaturesTitle: 'What sets us apart',
    whyUsIndex: `- Why us`,
    whyUsTitle: `Our Benefits & Advantages`,
    workingIndex: `- Working with us`,
    workingTitle: `Our Customers`,
    aboutTitle: `About eMasters`,
    refinedIndex: `Online Gaming Refined`,
    refinedTitle: `The Idea And Execution`,
    meetIndex: `- Meet The Team`,
    meetTitle: `The People Behind eMasters`,
    missionIndex: `- Our Mission`,
    missionTitle: `Removing Tournament Complexity`,
    helpusIndex: `- Who's Helping Us?`,
    helpusTitle: `Our Customers And Partners`,
    joinTeamIndex: `Join the Team`,
    joinTeamLink: `Careers Page`,
    investorIndex: `Become an Investor`,
    investorLink: `Learn How`,
    coFriendsIndex: `- Co-op with friends`,
    coFriendsTitle: `We Play With The Best`,
    familyIndex: `- The Extended Family`,
    familyTitle: `People Playing With eMasters`,
    faqTitle: `FAQ`,
    contactIndex: `- Connect with us`,
    contactTitle: `Contact Us`,
    contactTitle1: `eMasters`,
    contactTitle2: `1014 Capp St, San Francisco CA 94110`,
    downloadIndex: `- Download Our App`,
    downloadTitle: `Download the eMasters App`,
    needHelpIndex: `Need Help?`,
    needHelpLink: `Support Page`,
    windowsVersion: `Windows Version`,
    macVersion: `Mac Version`,
    linuxVersion: `Linux Version`,
}
const labels_cn = {
    basicTitle: `基本页面`,
    basicTitle2: `Detracto tincidunt constituto qui id, ex sit soleat habemus conceptam, et tation tollit nec.`,
    partnersTitle: `Partners`,
    joinIndex: `- Join the challenge`,
    joinTitle: `Play. Improve. Win!`,
    gameIndex: `- More coming soon`,
    gameTitle: `Games We Support`,
    featuresTitle: 'Features',
    whatFeaturesIndex: '- What is eMasters',
    whatFeaturesTitle: 'What sets us apart',
    whyUsIndex: `- Why us`,
    whyUsTitle: `Our Benefits & Advantages`,
    workingIndex: `- Working with us`,
    workingTitle: `Our Customers`,
    aboutTitle: `About eMasters`,
    refinedIndex: `Online Gaming Refined`,
    refinedTitle: `The Idea And Execution`,
    meetIndex: `- Meet The Team`,
    meetTitle: `The People Behind eMasters`,
    missionIndex: `- Our Mission`,
    missionTitle: `Removing Tournament Complexity`,
    helpusIndex: `- Who's Helping Us?`,
    helpusTitle: `Our Customers And Partners`,
    joinTeamIndex: `Join the Team`,
    joinTeamLink: `Careers Page`,
    investorIndex: `Become an Investor`,
    investorLink: `Learn How`,
    coFriendsIndex: `- Co-op with friends`,
    coFriendsTitle: `We Play With The Best`,
    familyIndex: `- The Extended Family`,
    familyTitle: `People Playing With eMasters`,
    faqTitle: `FAQ`,
    contactIndex: `- Connect with us`,
    contactTitle: `Contact Us`,
    contactTitle1: `eMasters`,
    contactTitle2: `1014 Capp St, San Francisco CA 94110`,
    downloadIndex: `- Download Our App`,
    downloadTitle: `Download the eMasters App`,
    needHelpIndex: `Need Help?`,
    needHelpLink: `Support Page`,
    windowsVersion: `Windows Version`,
    macVersion: `Mac Version`,
    linuxVersion: `Linux Version`,
}
const labels_pt = {
    basicTitle: `página básica`,
    basicTitle2: `Detracto tincidunt constituto qui id, ex sit soleat habemus conceptam, et tation tollit nec.`,
    partnersTitle: `Partners`,
    joinIndex: `- Join the challenge`,
    joinTitle: `Play. Improve. Win!`,
    gameIndex: `- More coming soon`,
    gameTitle: `Games We Support`,
    featuresTitle: 'Features',
    whatFeaturesIndex: '- What is eMasters',
    whatFeaturesTitle: 'What sets us apart',
    whyUsIndex: `- Why us`,
    whyUsTitle: `Our Benefits & Advantages`,
    workingIndex: `- Working with us`,
    workingTitle: `Our Customers`,
    aboutTitle: `About eMasters`,
    refinedIndex: `Online Gaming Refined`,
    refinedTitle: `The Idea And Execution`,
    meetIndex: `- Meet The Team`,
    meetTitle: `The People Behind eMasters`,
    missionIndex: `- Our Mission`,
    missionTitle: `Removing Tournament Complexity`,
    helpusIndex: `- Who's Helping Us?`,
    helpusTitle: `Our Customers And Partners`,
    joinTeamIndex: `Join the Team`,
    joinTeamLink: `Careers Page`,
    investorIndex: `Become an Investor`,
    investorLink: `Learn How`,
    coFriendsIndex: `- Co-op with friends`,
    coFriendsTitle: `We Play With The Best`,
    familyIndex: `- The Extended Family`,
    familyTitle: `People Playing With eMasters`,
    faqTitle: `FAQ`,
    contactIndex: `- Connect with us`,
    contactTitle: `Contact Us`,
    contactTitle1: `eMasters`,
    contactTitle2: `1014 Capp St, San Francisco CA 94110`,
    downloadIndex: `- Download Our App`,
    downloadTitle: `Download the eMasters App`,
    needHelpIndex: `Need Help?`,
    needHelpLink: `Support Page`,
    windowsVersion: `Windows Version`,
    macVersion: `Mac Version`,
    linuxVersion: `Linux Version`,
}
export  { labels_cn, labels_en, labels_pt}